theme: jekyll-theme-slate
title: Translation
description: Translation for Speedcubing
google_analytics: UA-141207758-2
minimal:
  social_links:
    twitter: kawam1123
    github: kawam1123
    instagram: kawam1123cuber