theme: jekyll-theme-slate
title: 日本語翻訳
description: スピードキューブ関連ドキュメントの翻訳（英語→日本語）
google_analytics: UA-141207758-2
minimal:
  social_links:
    twitter: kawam1123
    github: kawam1123
    instagram: kawam1123cuber